version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: 3dforma-web
    restart: unless-stopped
    ports:
      - "5678:80"
    volumes:
      # Точка со слешем (./) означает "текущая папка". 
      # Portainer сам смонтирует все HTML-файлы из репозитория в Nginx.
      - ./:/usr/share/nginx/html:ro
